### ISSUE TITLE
Function 2: get_polls_from_user(user_id, num=5)

### ISSUE THREAD

**Issue by Radascript** [UBC-MDS/tweepypoll#11]
- Write the function
- Test the function

**Comment by gn385x** [comment]
My branch for this function code can be found here: https://github.com/UBC-MDS/tweepypoll/tree/python_get_polls_from_users

**Comment by gn385x** [comment]
Updates:

- [ ] Number of polls: When using Client.get_users_tweets, it will return maximum 100 most recent tweets of the user per request (note: with our account, the maximum number of tweets we can pull is 3200). On the other hand, majority of tweets do not have a poll. Hence, I settle to just include the 100 most recent tweets; and a lot of times there will be no poll_id returned. 
- [x] Can't use environmental variable for bearer_token yet
