### ISSUE TITLE
GitHub actions workflows

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#31]
<img width="758" alt="Screen Shot 2022-01-24 at 3 28 51 PM" src="https://user-images.githubusercontent.com/94651544/150882280-161a4fbd-4d7b-4029-91b1-c0d969b143cc.png">

**Comment by gn385x** [comment]
@xiangwxt takes care of **cd** part
@gn385x takes care of **ci** part

**Comment by gn385x** [comment]
I finished my CI part. just need your approval for my PR to update pyproject.toml file - here: https://github.com/UBC-MDS/tweepypoll/pull/35
<img width="1302" alt="Screen Shot 2022-01-28 at 6 12 30 PM" src="https://user-images.githubusercontent.com/94651544/151643321-c2aabad6-82fe-4487-b7e7-7f0d711cf17f.png">

**Comment by xiangwxt** [comment]
![Screen Shot 2022-01-29 at 12 50 22 PM](https://user-images.githubusercontent.com/90027336/151677247-251acb0e-75e4-46a3-9e9e-c7c66957e0b3.png)
I finished the cd part.
