### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#4]
<img width="654" alt="Screen Shot 2022-01-14 at 9 18 39 AM" src="https://user-images.githubusercontent.com/94651544/149557492-d10f0228-f5ab-4792-8258-8b0d05088218.png">

**Comment by gn385x** [comment]
hey @xiangwxt, let's discuss our ideas and updates regarding project structure here! 
we are done with 1, 2, 3. could you give a brief update on which bullet points you are working on? thanks!

**Comment by xiangwxt** [comment]
Hi @gn385x I've finished 4, I'm working on conduct.md and contributing.md.

**Comment by gn385x** [comment]
hey @xiangwxt , my pull request to edit the README.md file is up! - https://github.com/UBC-MDS/tweepypoll/pull/7
this is for bullet point 7.
