### ISSUE TITLE
Initiate review request

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#42]
<img width="741" alt="Screen Shot 2022-01-31 at 2 18 14 PM" src="https://user-images.githubusercontent.com/94651544/151882424-24bba0f1-aaa2-4802-976e-9c54cba689de.png">

Template: https://github.com/pyOpenSci/software-review/blob/main/.github/ISSUE_TEMPLATE/submit-software-for-review.md

**Comment by xiangwxt** [comment]
Finished.
